 # Importing all the required libraries
import requests
import streamlit as st
import time
from logger import MyLogger

# st.title("View All History")
st.set_page_config(page_title="View All History", layout="centered")
st.write("View All History here")
# Initiating logger
logger = MyLogger.get_logger(__name__)

headers = {
    'Authorization': 'Bearer 1234' ,
    'Content-Type': 'application/json'
}

# Storing App URL in a variable
API_URL_db = "http://127.0.0.1:8080/data_all_db"
# Setting up the sidebar
if st.button("View History"):
        start_time= time.perf_counter()
        logger.info(
                f"Program starts now: {start_time}"
        )
        try:
                response = requests.post(API_URL_db ,headers=headers)
                if response.status_code == 200 :
                    response_data = response.json()
                    if "error" in response_data:
                        st.error(response_data["error"])
                    else: 
                        hist_response= response.json()
                        st.header("All records of all users")
                        df1=st.dataframe(hist_response)
                        st.header("Graphical Representations")
                        st.line_chart(hist_response, y='sentiment')
                        logger.info(
                f"this the json response for the data generated by the api: {hist_response}"
            )
        except Exception as e:
                st.error(f"an error occured : {e}")